/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class AudioFilterAudioProcessorEditor  : public AudioProcessorEditor,
										public SliderListener
{
public:
    AudioFilterAudioProcessorEditor (AudioFilterAudioProcessor* ownerFilter);
    ~AudioFilterAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
	void timerCallback();
	void paint(Graphics&) override;
	void resized() override;
	void sliderValueChanged(Slider*);

private:
	Label cutoffLabel;
	Slider cutoffSlider;
	ScopedPointer<ResizableCornerComponent> resizer;
	ComponentBoundsConstrainer resizeLimits;

	AudioPlayHead::CurrentPositionInfo lastDisplayedPosition;

	AudioFilterAudioProcessor* getProcessor() const
	{
		return static_cast <AudioFilterAudioProcessor*> (getAudioProcessor());
	}

};


#endif  // PLUGINEDITOR_H_INCLUDED
